<?php
//move echo code to bottom
//get one random code language
echo $lang[array_rand($lang, 1)]['code'];
//get one random name language
echo $lang[array_rand($lang, 1)]['name'];

$lang = [
    ['code' => 'af', 'name' => 'Afrikaans'],
    ['code' => 'af-NA', 'name' => 'Afrikaans (Namibia)'],
    ['code' => 'af-ZA', 'name' => 'Afrikaans (South Africa)'],
    ['code' => 'ak', 'name' => 'Akan'],
    ['code' => 'ak-GH', 'name' => 'Akan (Ghana)'],
    ['code' => 'sq', 'name' => 'Albanian'],
    ['code' => 'sq-AL', 'name' => 'Albanian (Albania)'],
    ['code' => 'sq-XK', 'name' => 'Albanian (Kosovo)'],
    ['code' => 'sq-MK', 'name' => 'Albanian (Macedonia)'],
    ['code' => 'am', 'name' => 'Amharic'],
    ['code' => 'am-ET', 'name' => 'Amharic (Ethiopia)'],
    ['code' => 'ar', 'name' => 'Arabic'],
    ['code' => 'ar-DZ', 'name' => 'Arabic (Algeria)'],
    ['code' => 'ar-BH', 'name' => 'Arabic (Bahrain)'],
    ['code' => 'ar-TD', 'name' => 'Arabic (Chad)'],
    ['code' => 'ar-KM', 'name' => 'Arabic (Comoros)'],
    ['code' => 'ar-DJ', 'name' => 'Arabic (Djibouti)'],
    ['code' => 'ar-EG', 'name' => 'Arabic (Egypt)'],
    ['code' => 'ar-ER', 'name' => 'Arabic (Eritrea)'],
    ['code' => 'ar-IQ', 'name' => 'Arabic (Iraq)'],
    ['code' => 'ar-IL', 'name' => 'Arabic (Israel)'],
    ['code' => 'ar-JO', 'name' => 'Arabic (Jordan)'],
    ['code' => 'ar-KW', 'name' => 'Arabic (Kuwait)'],
    ['code' => 'ar-LB', 'name' => 'Arabic (Lebanon)'],
    ['code' => 'ar-LY', 'name' => 'Arabic (Libya)'],
    ['code' => 'ar-MR', 'name' => 'Arabic (Mauritania)'],
    ['code' => 'ar-MA', 'name' => 'Arabic (Morocco)'],
    ['code' => 'ar-OM', 'name' => 'Arabic (Oman)'],
    ['code' => 'ar-PS', 'name' => 'Arabic (Palestinian Territories)'],
    ['code' => 'ar-QA', 'name' => 'Arabic (Qatar)'],
    ['code' => 'ar-SA', 'name' => 'Arabic (Saudi Arabia)'],
    ['code' => 'ar-SO', 'name' => 'Arabic (Somalia)'],
    ['code' => 'ar-SS', 'name' => 'Arabic (South Sudan)'],
    ['code' => 'ar-SD', 'name' => 'Arabic (Sudan)'],
    ['code' => 'ar-SY', 'name' => 'Arabic (Syria)'],
    ['code' => 'ar-TN', 'name' => 'Arabic (Tunisia)'],
    ['code' => 'ar-AE', 'name' => 'Arabic (United Arab Emirates)'],
    ['code' => 'ar-EH', 'name' => 'Arabic (Western Sahara)'],
    ['code' => 'ar-YE', 'name' => 'Arabic (Yemen)'],
    ['code' => 'hy', 'name' => 'Armenian'],
    ['code' => 'hy-AM', 'name' => 'Armenian (Armenia)'],
    ['code' => 'as', 'name' => 'Assamese'],
    ['code' => 'as-IN', 'name' => 'Assamese (India)'],
    ['code' => 'az', 'name' => 'Azerbaijani'],
    ['code' => 'az-AZ', 'name' => 'Azerbaijani (Azerbaijan)'],
    ['code' => 'az-Cyrl-AZ', 'name' => 'Azerbaijani (Cyrillic, Azerbaijan)'],
    ['code' => 'az-Cyrl', 'name' => 'Azerbaijani (Cyrillic)'],
    ['code' => 'az-Latn-AZ', 'name' => 'Azerbaijani (Latin, Azerbaijan)'],
    ['code' => 'az-Latn', 'name' => 'Azerbaijani (Latin)'],
    ['code' => 'bm', 'name' => 'Bambara'],
    ['code' => 'bm-Latn-ML', 'name' => 'Bambara (Latin, Mali)'],
    ['code' => 'bm-Latn', 'name' => 'Bambara (Latin)'],
    ['code' => 'eu', 'name' => 'Basque'],
    ['code' => 'eu-ES', 'name' => 'Basque (Spain)'],
    ['code' => 'be', 'name' => 'Belarusian'],
    ['code' => 'be-BY', 'name' => 'Belarusian (Belarus)'],
    ['code' => 'bn', 'name' => 'Bengali'],
    ['code' => 'bn-BD', 'name' => 'Bengali (Bangladesh)'],
    ['code' => 'bn-IN', 'name' => 'Bengali (India)'],
    ['code' => 'bs', 'name' => 'Bosnian'],
    ['code' => 'bs-BA', 'name' => 'Bosnian (Bosnia & Herzegovina)'],
    ['code' => 'bs-Cyrl-BA', 'name' => 'Bosnian (Cyrillic, Bosnia & Herzegovina)'],
    ['code' => 'bs-Cyrl', 'name' => 'Bosnian (Cyrillic)'],
    ['code' => 'bs-Latn-BA', 'name' => 'Bosnian (Latin, Bosnia & Herzegovina)'],
    ['code' => 'bs-Latn', 'name' => 'Bosnian (Latin)'],
    ['code' => 'br', 'name' => 'Breton'],
    ['code' => 'br-FR', 'name' => 'Breton (France)'],
    ['code' => 'bg', 'name' => 'Bulgarian'],
    ['code' => 'bg-BG', 'name' => 'Bulgarian (Bulgaria)'],
    ['code' => 'my', 'name' => 'Burmese'],
    ['code' => 'my-MM', 'name' => 'Burmese (Myanmar (Burma))'],
    ['code' => 'ca', 'name' => 'Catalan'],
    ['code' => 'ca-AD', 'name' => 'Catalan (Andorra)'],
    ['code' => 'ca-FR', 'name' => 'Catalan (France)'],
    ['code' => 'ca-IT', 'name' => 'Catalan (Italy)'],
    ['code' => 'ca-ES', 'name' => 'Catalan (Spain)'],
    ['code' => 'zh', 'name' => 'Chinese'],
    ['code' => 'zh-CN', 'name' => 'Chinese (China)'],
    ['code' => 'zh-HK', 'name' => 'Chinese (Hong Kong SAR China)'],
    ['code' => 'zh-MO', 'name' => 'Chinese (Macau SAR China)'],
    ['code' => 'zh-Hans-CN', 'name' => 'Chinese (Simplified, China)'],
    ['code' => 'zh-Hans-HK', 'name' => 'Chinese (Simplified, Hong Kong SAR China)'],
    ['code' => 'zh-Hans-MO', 'name' => 'Chinese (Simplified, Macau SAR China)'],
    ['code' => 'zh-Hans-SG', 'name' => 'Chinese (Simplified, Singapore)'],
    ['code' => 'zh-Hans', 'name' => 'Chinese (Simplified)'],
    ['code' => 'zh-SG', 'name' => 'Chinese (Singapore)'],
    ['code' => 'zh-TW', 'name' => 'Chinese (Taiwan)'],
    ['code' => 'zh-Hant-HK', 'name' => 'Chinese (Traditional, Hong Kong SAR China)'],
    ['code' => 'zh-Hant-MO', 'name' => 'Chinese (Traditional, Macau SAR China)'],
    ['code' => 'zh-Hant-TW', 'name' => 'Chinese (Traditional, Taiwan)'],
    ['code' => 'zh-Hant', 'name' => 'Chinese (Traditional)'],
    ['code' => 'kw', 'name' => 'Cornish'],
    ['code' => 'kw-GB', 'name' => 'Cornish (United Kingdom)'],
    ['code' => 'hr', 'name' => 'Croatian'],
    ['code' => 'hr-BA', 'name' => 'Croatian (Bosnia & Herzegovina)'],
    ['code' => 'hr-HR', 'name' => 'Croatian (Croatia)'],
    ['code' => 'cs', 'name' => 'Czech'],
    ['code' => 'cs-CZ', 'name' => 'Czech (Czech Republic)'],
    ['code' => 'da', 'name' => 'Danish'],
    ['code' => 'da-DK', 'name' => 'Danish (Denmark)'],
    ['code' => 'da-GL', 'name' => 'Danish (Greenland)'],
    ['code' => 'nl', 'name' => 'Dutch'],
    ['code' => 'nl-AW', 'name' => 'Dutch (Aruba)'],
    ['code' => 'nl-BE', 'name' => 'Dutch (Belgium)'],
    ['code' => 'nl-BQ', 'name' => 'Dutch (Caribbean Netherlands)'],
    ['code' => 'nl-CW', 'name' => 'Dutch (Curaçao)'],
    ['code' => 'nl-NL', 'name' => 'Dutch (Netherlands)'],
    ['code' => 'nl-SX', 'name' => 'Dutch (Sint Maarten)'],
    ['code' => 'nl-SR', 'name' => 'Dutch (Suriname)'],
    ['code' => 'dz', 'name' => 'Dzongkha'],
    ['code' => 'dz-BT', 'name' => 'Dzongkha (Bhutan)'],
    ['code' => 'en', 'name' => 'English'],
    ['code' => 'en-AS', 'name' => 'English (American Samoa)'],
    ['code' => 'en-AI', 'name' => 'English (Anguilla)'],
    ['code' => 'en-AG', 'name' => 'English (Antigua & Barbuda)'],
    ['code' => 'en-AU', 'name' => 'English (Australia)'],
    ['code' => 'en-BS', 'name' => 'English (Bahamas)'],
    ['code' => 'en-BB', 'name' => 'English (Barbados)'],
    ['code' => 'en-BE', 'name' => 'English (Belgium)'],
    ['code' => 'en-BZ', 'name' => 'English (Belize)'],
    ['code' => 'en-BM', 'name' => 'English (Bermuda)'],
    ['code' => 'en-BW', 'name' => 'English (Botswana)'],
    ['code' => 'en-IO', 'name' => 'English (British Indian Ocean Territory)'],
    ['code' => 'en-VG', 'name' => 'English (British Virgin Islands)'],
    ['code' => 'en-CM', 'name' => 'English (Cameroon)'],
    ['code' => 'en-CA', 'name' => 'English (Canada)'],
    ['code' => 'en-KY', 'name' => 'English (Cayman Islands)'],
    ['code' => 'en-CX', 'name' => 'English (Christmas Island)'],
    ['code' => 'en-CC', 'name' => 'English (Cocos (Keeling) Islands)'],
    ['code' => 'en-CK', 'name' => 'English (Cook Islands)'],
    ['code' => 'en-DG', 'name' => 'English (Diego Garcia)'],
    ['code' => 'en-DM', 'name' => 'English (Dominica)'],
    ['code' => 'en-ER', 'name' => 'English (Eritrea)'],
    ['code' => 'en-FK', 'name' => 'English (Falkland Islands)'],
    ['code' => 'en-FJ', 'name' => 'English (Fiji)'],
    ['code' => 'en-GM', 'name' => 'English (Gambia)'],
    ['code' => 'en-GH', 'name' => 'English (Ghana)'],
    ['code' => 'en-GI', 'name' => 'English (Gibraltar)'],
    ['code' => 'en-GD', 'name' => 'English (Grenada)'],
    ['code' => 'en-GU', 'name' => 'English (Guam)'],
    ['code' => 'en-GG', 'name' => 'English (Guernsey)'],
    ['code' => 'en-GY', 'name' => 'English (Guyana)'],
    ['code' => 'en-HK', 'name' => 'English (Hong Kong SAR China)'],
    ['code' => 'en-IN', 'name' => 'English (India)'],
    ['code' => 'en-IE', 'name' => 'English (Ireland)'],
    ['code' => 'en-IM', 'name' => 'English (Isle of Man)'],
    ['code' => 'en-JM', 'name' => 'English (Jamaica)'],
    ['code' => 'en-JE', 'name' => 'English (Jersey)'],
    ['code' => 'en-KE', 'name' => 'English (Kenya)'],
    ['code' => 'en-KI', 'name' => 'English (Kiribati)'],
    ['code' => 'en-LS', 'name' => 'English (Lesotho)'],
    ['code' => 'en-LR', 'name' => 'English (Liberia)'],
    ['code' => 'en-MO', 'name' => 'English (Macau SAR China)'],
    ['code' => 'en-MG', 'name' => 'English (Madagascar)'],
    ['code' => 'en-MW', 'name' => 'English (Malawi)'],
    ['code' => 'en-MY', 'name' => 'English (Malaysia)'],
    ['code' => 'en-MT', 'name' => 'English (Malta)'],
    ['code' => 'en-MH', 'name' => 'English (Marshall Islands)'],
    ['code' => 'en-MU', 'name' => 'English (Mauritius)'],
    ['code' => 'en-FM', 'name' => 'English (Micronesia)'],
    ['code' => 'en-MS', 'name' => 'English (Montserrat)'],
    ['code' => 'en-NA', 'name' => 'English (Namibia)'],
    ['code' => 'en-NR', 'name' => 'English (Nauru)'],
    ['code' => 'en-NZ', 'name' => 'English (New Zealand)'],
    ['code' => 'en-NG', 'name' => 'English (Nigeria)'],
    ['code' => 'en-NU', 'name' => 'English (Niue)'],
    ['code' => 'en-NF', 'name' => 'English (Norfolk Island)'],
    ['code' => 'en-MP', 'name' => 'English (Northern Mariana Islands)'],
    ['code' => 'en-PK', 'name' => 'English (Pakistan)'],
    ['code' => 'en-PW', 'name' => 'English (Palau)'],
    ['code' => 'en-PG', 'name' => 'English (Papua New Guinea)'],
    ['code' => 'en-PH', 'name' => 'English (Philippines)'],
    ['code' => 'en-PN', 'name' => 'English (Pitcairn Islands)'],
    ['code' => 'en-PR', 'name' => 'English (Puerto Rico)'],
    ['code' => 'en-RW', 'name' => 'English (Rwanda)'],
    ['code' => 'en-WS', 'name' => 'English (Samoa)'],
    ['code' => 'en-SC', 'name' => 'English (Seychelles)'],
    ['code' => 'en-SL', 'name' => 'English (Sierra Leone)'],
    ['code' => 'en-SG', 'name' => 'English (Singapore)'],
    ['code' => 'en-SX', 'name' => 'English (Sint Maarten)'],
    ['code' => 'en-SB', 'name' => 'English (Solomon Islands)'],
    ['code' => 'en-ZA', 'name' => 'English (South Africa)'],
    ['code' => 'en-SS', 'name' => 'English (South Sudan)'],
    ['code' => 'en-SH', 'name' => 'English (St. Helena)'],
    ['code' => 'en-KN', 'name' => 'English (St. Kitts & Nevis)'],
    ['code' => 'en-LC', 'name' => 'English (St. Lucia)'],
    ['code' => 'en-VC', 'name' => 'English (St. Vincent & Grenadines)'],
    ['code' => 'en-SD', 'name' => 'English (Sudan)'],
    ['code' => 'en-SZ', 'name' => 'English (Swaziland)'],
    ['code' => 'en-TZ', 'name' => 'English (Tanzania)'],
    ['code' => 'en-TK', 'name' => 'English (Tokelau)'],
    ['code' => 'en-TO', 'name' => 'English (Tonga)'],
    ['code' => 'en-TT', 'name' => 'English (Trinidad & Tobago)'],
    ['code' => 'en-TC', 'name' => 'English (Turks & Caicos Islands)'],
    ['code' => 'en-TV', 'name' => 'English (Tuvalu)'],
    ['code' => 'en-UM', 'name' => 'English (U.S. Outlying Islands)'],
    ['code' => 'en-VI', 'name' => 'English (U.S. Virgin Islands)'],
    ['code' => 'en-UG', 'name' => 'English (Uganda)'],
    ['code' => 'en-GB', 'name' => 'English (United Kingdom)'],
    ['code' => 'en-US', 'name' => 'English (United States)'],
    ['code' => 'en-VU', 'name' => 'English (Vanuatu)'],
    ['code' => 'en-ZM', 'name' => 'English (Zambia)'],
    ['code' => 'en-ZW', 'name' => 'English (Zimbabwe)'],
    ['code' => 'eo', 'name' => 'Esperanto'],
    ['code' => 'et', 'name' => 'Estonian'],
    ['code' => 'et-EE', 'name' => 'Estonian (Estonia)'],
    ['code' => 'ee', 'name' => 'Ewe'],
    ['code' => 'ee-GH', 'name' => 'Ewe (Ghana)'],
    ['code' => 'ee-TG', 'name' => 'Ewe (Togo)'],
    ['code' => 'fo', 'name' => 'Faroese'],
    ['code' => 'fo-FO', 'name' => 'Faroese (Faroe Islands)'],
    ['code' => 'fi', 'name' => 'Finnish'],
    ['code' => 'fi-FI', 'name' => 'Finnish (Finland)'],
    ['code' => 'fr', 'name' => 'French'],
    ['code' => 'fr-DZ', 'name' => 'French (Algeria)'],
    ['code' => 'fr-BE', 'name' => 'French (Belgium)'],
    ['code' => 'fr-BJ', 'name' => 'French (Benin)'],
    ['code' => 'fr-BF', 'name' => 'French (Burkina Faso)'],
    ['code' => 'fr-BI', 'name' => 'French (Burundi)'],
    ['code' => 'fr-CM', 'name' => 'French (Cameroon)'],
    ['code' => 'fr-CA', 'name' => 'French (Canada)'],
    ['code' => 'fr-CF', 'name' => 'French (Central African Republic)'],
    ['code' => 'fr-TD', 'name' => 'French (Chad)'],
    ['code' => 'fr-KM', 'name' => 'French (Comoros)'],
    ['code' => 'fr-CG', 'name' => 'French (Congo - Brazzaville)'],
    ['code' => 'fr-CD', 'name' => 'French (Congo - Kinshasa)'],
    ['code' => 'fr-CI', 'name' => 'French (Côte d’Ivoire)'],
    ['code' => 'fr-DJ', 'name' => 'French (Djibouti)'],
    ['code' => 'fr-GQ', 'name' => 'French (Equatorial Guinea)'],
    ['code' => 'fr-FR', 'name' => 'French (France)'],
    ['code' => 'fr-GF', 'name' => 'French (French Guiana)'],
    ['code' => 'fr-PF', 'name' => 'French (French Polynesia)'],
    ['code' => 'fr-GA', 'name' => 'French (Gabon)'],
    ['code' => 'fr-GP', 'name' => 'French (Guadeloupe)'],
    ['code' => 'fr-GN', 'name' => 'French (Guinea)'],
    ['code' => 'fr-HT', 'name' => 'French (Haiti)'],
    ['code' => 'fr-LU', 'name' => 'French (Luxembourg)'],
    ['code' => 'fr-MG', 'name' => 'French (Madagascar)'],
    ['code' => 'fr-ML', 'name' => 'French (Mali)'],
    ['code' => 'fr-MQ', 'name' => 'French (Martinique)'],
    ['code' => 'fr-MR', 'name' => 'French (Mauritania)'],
    ['code' => 'fr-MU', 'name' => 'French (Mauritius)'],
    ['code' => 'fr-YT', 'name' => 'French (Mayotte)'],
    ['code' => 'fr-MC', 'name' => 'French (Monaco)'],
    ['code' => 'fr-MA', 'name' => 'French (Morocco)'],
    ['code' => 'fr-NC', 'name' => 'French (New Caledonia)'],
    ['code' => 'fr-NE', 'name' => 'French (Niger)'],
    ['code' => 'fr-RE', 'name' => 'French (Réunion)'],
    ['code' => 'fr-RW', 'name' => 'French (Rwanda)'],
    ['code' => 'fr-SN', 'name' => 'French (Senegal)'],
    ['code' => 'fr-SC', 'name' => 'French (Seychelles)'],
    ['code' => 'fr-BL', 'name' => 'French (St. Barthélemy)'],
    ['code' => 'fr-MF', 'name' => 'French (St. Martin)'],
    ['code' => 'fr-PM', 'name' => 'French (St. Pierre & Miquelon)'],
    ['code' => 'fr-CH', 'name' => 'French (Switzerland)'],
    ['code' => 'fr-SY', 'name' => 'French (Syria)'],
    ['code' => 'fr-TG', 'name' => 'French (Togo)'],
    ['code' => 'fr-TN', 'name' => 'French (Tunisia)'],
    ['code' => 'fr-VU', 'name' => 'French (Vanuatu)'],
    ['code' => 'fr-WF', 'name' => 'French (Wallis & Futuna)'],
    ['code' => 'ff', 'name' => 'Fulah'],
    ['code' => 'ff-CM', 'name' => 'Fulah (Cameroon)'],
    ['code' => 'ff-GN', 'name' => 'Fulah (Guinea)'],
    ['code' => 'ff-MR', 'name' => 'Fulah (Mauritania)'],
    ['code' => 'ff-SN', 'name' => 'Fulah (Senegal)'],
    ['code' => 'gl', 'name' => 'Galician'],
    ['code' => 'gl-ES', 'name' => 'Galician (Spain)'],
    ['code' => 'lg', 'name' => 'Ganda'],
    ['code' => 'lg-UG', 'name' => 'Ganda (Uganda)'],
    ['code' => 'ka', 'name' => 'Georgian'],
    ['code' => 'ka-GE', 'name' => 'Georgian (Georgia)'],
    ['code' => 'de', 'name' => 'German'],
    ['code' => 'de-AT', 'name' => 'German (Austria)'],
    ['code' => 'de-BE', 'name' => 'German (Belgium)'],
    ['code' => 'de-DE', 'name' => 'German (Germany)'],
    ['code' => 'de-LI', 'name' => 'German (Liechtenstein)'],
    ['code' => 'de-LU', 'name' => 'German (Luxembourg)'],
    ['code' => 'de-CH', 'name' => 'German (Switzerland)'],
    ['code' => 'el', 'name' => 'Greek'],
    ['code' => 'el-CY', 'name' => 'Greek (Cyprus)'],
    ['code' => 'el-GR', 'name' => 'Greek (Greece)'],
    ['code' => 'gu', 'name' => 'Gujarati'],
    ['code' => 'gu-IN', 'name' => 'Gujarati (India)'],
    ['code' => 'ha', 'name' => 'Hausa'],
    ['code' => 'ha-GH', 'name' => 'Hausa (Ghana)'],
    ['code' => 'ha-Latn-GH', 'name' => 'Hausa (Latin, Ghana)'],
    ['code' => 'ha-Latn-NE', 'name' => 'Hausa (Latin, Niger)'],
    ['code' => 'ha-Latn-NG', 'name' => 'Hausa (Latin, Nigeria)'],
    ['code' => 'ha-Latn', 'name' => 'Hausa (Latin)'],
    ['code' => 'ha-NE', 'name' => 'Hausa (Niger)'],
    ['code' => 'ha-NG', 'name' => 'Hausa (Nigeria)'],
    ['code' => 'he', 'name' => 'Hebrew'],
    ['code' => 'he-IL', 'name' => 'Hebrew (Israel)'],
    ['code' => 'hi', 'name' => 'Hindi'],
    ['code' => 'hi-IN', 'name' => 'Hindi (India)'],
    ['code' => 'hu', 'name' => 'Hungarian'],
    ['code' => 'hu-HU', 'name' => 'Hungarian (Hungary)'],
    ['code' => 'is', 'name' => 'Icelandic'],
    ['code' => 'is-IS', 'name' => 'Icelandic (Iceland)'],
    ['code' => 'ig', 'name' => 'Igbo'],
    ['code' => 'ig-NG', 'name' => 'Igbo (Nigeria)'],
    ['code' => 'id', 'name' => 'Indonesian'],
    ['code' => 'id-ID', 'name' => 'Indonesian (Indonesia)'],
    ['code' => 'ga', 'name' => 'Irish'],
    ['code' => 'ga-IE', 'name' => 'Irish (Ireland)'],
    ['code' => 'it', 'name' => 'Italian'],
    ['code' => 'it-IT', 'name' => 'Italian (Italy)'],
    ['code' => 'it-SM', 'name' => 'Italian (San Marino)'],
    ['code' => 'it-CH', 'name' => 'Italian (Switzerland)'],
    ['code' => 'ja', 'name' => 'Japanese'],
    ['code' => 'ja-JP', 'name' => 'Japanese (Japan)'],
    ['code' => 'kl', 'name' => 'Kalaallisut'],
    ['code' => 'kl-GL', 'name' => 'Kalaallisut (Greenland)'],
    ['code' => 'kn', 'name' => 'Kannada'],
    ['code' => 'kn-IN', 'name' => 'Kannada (India)'],
    ['code' => 'ks', 'name' => 'Kashmiri'],
    ['code' => 'ks-Arab-IN', 'name' => 'Kashmiri (Arabic, India)'],
    ['code' => 'ks-Arab', 'name' => 'Kashmiri (Arabic)'],
    ['code' => 'ks-IN', 'name' => 'Kashmiri (India)'],
    ['code' => 'kk', 'name' => 'Kazakh'],
    ['code' => 'kk-Cyrl-KZ', 'name' => 'Kazakh (Cyrillic, Kazakhstan)'],
    ['code' => 'kk-Cyrl', 'name' => 'Kazakh (Cyrillic)'],
    ['code' => 'kk-KZ', 'name' => 'Kazakh (Kazakhstan)'],
    ['code' => 'km', 'name' => 'Khmer'],
    ['code' => 'km-KH', 'name' => 'Khmer (Cambodia)'],
    ['code' => 'ki', 'name' => 'Kikuyu'],
    ['code' => 'ki-KE', 'name' => 'Kikuyu (Kenya)'],
    ['code' => 'rw', 'name' => 'Kinyarwanda'],
    ['code' => 'rw-RW', 'name' => 'Kinyarwanda (Rwanda)'],
    ['code' => 'ko', 'name' => 'Korean'],
    ['code' => 'ko-KP', 'name' => 'Korean (North Korea)'],
    ['code' => 'ko-KR', 'name' => 'Korean (South Korea)'],
    ['code' => 'ky', 'name' => 'Kyrgyz'],
    ['code' => 'ky-Cyrl-KG', 'name' => 'Kyrgyz (Cyrillic, Kyrgyzstan)'],
    ['code' => 'ky-Cyrl', 'name' => 'Kyrgyz (Cyrillic)'],
    ['code' => 'ky-KG', 'name' => 'Kyrgyz (Kyrgyzstan)'],
    ['code' => 'lo', 'name' => 'Lao'],
    ['code' => 'lo-LA', 'name' => 'Lao (Laos)'],
    ['code' => 'lv', 'name' => 'Latvian'],
    ['code' => 'lv-LV', 'name' => 'Latvian (Latvia)'],
    ['code' => 'ln', 'name' => 'Lingala'],
    ['code' => 'ln-AO', 'name' => 'Lingala (Angola)'],
    ['code' => 'ln-CF', 'name' => 'Lingala (Central African Republic)'],
    ['code' => 'ln-CG', 'name' => 'Lingala (Congo - Brazzaville)'],
    ['code' => 'ln-CD', 'name' => 'Lingala (Congo - Kinshasa)'],
    ['code' => 'lt', 'name' => 'Lithuanian'],
    ['code' => 'lt-LT', 'name' => 'Lithuanian (Lithuania)'],
    ['code' => 'lu', 'name' => 'Luba-Katanga'],
    ['code' => 'lu-CD', 'name' => 'Luba-Katanga (Congo - Kinshasa)'],
    ['code' => 'lb', 'name' => 'Luxembourgish'],
    ['code' => 'lb-LU', 'name' => 'Luxembourgish (Luxembourg)'],
    ['code' => 'mk', 'name' => 'Macedonian'],
    ['code' => 'mk-MK', 'name' => 'Macedonian (Macedonia)'],
    ['code' => 'mg', 'name' => 'Malagasy'],
    ['code' => 'mg-MG', 'name' => 'Malagasy (Madagascar)'],
    ['code' => 'ms', 'name' => 'Malay'],
    ['code' => 'ms-BN', 'name' => 'Malay (Brunei)'],
    ['code' => 'ms-Latn-BN', 'name' => 'Malay (Latin, Brunei)'],
    ['code' => 'ms-Latn-MY', 'name' => 'Malay (Latin, Malaysia)'],
    ['code' => 'ms-Latn-SG', 'name' => 'Malay (Latin, Singapore)'],
    ['code' => 'ms-Latn', 'name' => 'Malay (Latin)'],
    ['code' => 'ms-MY', 'name' => 'Malay (Malaysia)'],
    ['code' => 'ms-SG', 'name' => 'Malay (Singapore)'],
    ['code' => 'ml', 'name' => 'Malayalam'],
    ['code' => 'ml-IN', 'name' => 'Malayalam (India)'],
    ['code' => 'mt', 'name' => 'Maltese'],
    ['code' => 'mt-MT', 'name' => 'Maltese (Malta)'],
    ['code' => 'gv', 'name' => 'Manx'],
    ['code' => 'gv-IM', 'name' => 'Manx (Isle of Man)'],
    ['code' => 'mr', 'name' => 'Marathi'],
    ['code' => 'mr-IN', 'name' => 'Marathi (India)'],
    ['code' => 'mn', 'name' => 'Mongolian'],
    ['code' => 'mn-Cyrl-MN', 'name' => 'Mongolian (Cyrillic, Mongolia)'],
    ['code' => 'mn-Cyrl', 'name' => 'Mongolian (Cyrillic)'],
    ['code' => 'mn-MN', 'name' => 'Mongolian (Mongolia)'],
    ['code' => 'ne', 'name' => 'Nepali'],
    ['code' => 'ne-IN', 'name' => 'Nepali (India)'],
    ['code' => 'ne-NP', 'name' => 'Nepali (Nepal)'],
    ['code' => 'nd', 'name' => 'North Ndebele'],
    ['code' => 'nd-ZW', 'name' => 'North Ndebele (Zimbabwe)'],
    ['code' => 'se', 'name' => 'Northern Sami'],
    ['code' => 'se-FI', 'name' => 'Northern Sami (Finland)'],
    ['code' => 'se-NO', 'name' => 'Northern Sami (Norway)'],
    ['code' => 'se-SE', 'name' => 'Northern Sami (Sweden)'],
    ['code' => 'no', 'name' => 'Norwegian'],
    ['code' => 'no-NO', 'name' => 'Norwegian (Norway)'],
    ['code' => 'nb', 'name' => 'Norwegian Bokmål'],
    ['code' => 'nb-NO', 'name' => 'Norwegian Bokmål (Norway)'],
    ['code' => 'nb-SJ', 'name' => 'Norwegian Bokmål (Svalbard & Jan Mayen)'],
    ['code' => 'nn', 'name' => 'Norwegian Nynorsk'],
    ['code' => 'nn-NO', 'name' => 'Norwegian Nynorsk (Norway)'],
    ['code' => 'or', 'name' => 'Oriya'],
    ['code' => 'or-IN', 'name' => 'Oriya (India)'],
    ['code' => 'om', 'name' => 'Oromo'],
    ['code' => 'om-ET', 'name' => 'Oromo (Ethiopia)'],
    ['code' => 'om-KE', 'name' => 'Oromo (Kenya)'],
    ['code' => 'os', 'name' => 'Ossetic'],
    ['code' => 'os-GE', 'name' => 'Ossetic (Georgia)'],
    ['code' => 'os-RU', 'name' => 'Ossetic (Russia)'],
    ['code' => 'ps', 'name' => 'Pashto'],
    ['code' => 'ps-AF', 'name' => 'Pashto (Afghanistan)'],
    ['code' => 'fa', 'name' => 'Persian'],
    ['code' => 'fa-AF', 'name' => 'Persian (Afghanistan)'],
    ['code' => 'fa-IR', 'name' => 'Persian (Iran)'],
    ['code' => 'pl', 'name' => 'Polish'],
    ['code' => 'pl-PL', 'name' => 'Polish (Poland)'],
    ['code' => 'pt', 'name' => 'Portuguese'],
    ['code' => 'pt-AO', 'name' => 'Portuguese (Angola)'],
    ['code' => 'pt-BR', 'name' => 'Portuguese (Brazil)'],
    ['code' => 'pt-CV', 'name' => 'Portuguese (Cape Verde)'],
    ['code' => 'pt-GW', 'name' => 'Portuguese (Guinea-Bissau)'],
    ['code' => 'pt-MO', 'name' => 'Portuguese (Macau SAR China)'],
    ['code' => 'pt-MZ', 'name' => 'Portuguese (Mozambique)'],
    ['code' => 'pt-PT', 'name' => 'Portuguese (Portugal)'],
    ['code' => 'pt-ST', 'name' => 'Portuguese (São Tomé & Príncipe)'],
    ['code' => 'pt-TL', 'name' => 'Portuguese (Timor-Leste)'],
    ['code' => 'pa', 'name' => 'Punjabi'],
    ['code' => 'pa-Arab-PK', 'name' => 'Punjabi (Arabic, Pakistan)'],
    ['code' => 'pa-Arab', 'name' => 'Punjabi (Arabic)'],
    ['code' => 'pa-Guru-IN', 'name' => 'Punjabi (Gurmukhi, India)'],
    ['code' => 'pa-Guru', 'name' => 'Punjabi (Gurmukhi)'],
    ['code' => 'pa-IN', 'name' => 'Punjabi (India)'],
    ['code' => 'pa-PK', 'name' => 'Punjabi (Pakistan)'],
    ['code' => 'qu', 'name' => 'Quechua'],
    ['code' => 'qu-BO', 'name' => 'Quechua (Bolivia)'],
    ['code' => 'qu-EC', 'name' => 'Quechua (Ecuador)'],
    ['code' => 'qu-PE', 'name' => 'Quechua (Peru)'],
    ['code' => 'ro', 'name' => 'Romanian'],
    ['code' => 'ro-MD', 'name' => 'Romanian (Moldova)'],
    ['code' => 'ro-RO', 'name' => 'Romanian (Romania)'],
    ['code' => 'rm', 'name' => 'Romansh'],
    ['code' => 'rm-CH', 'name' => 'Romansh (Switzerland)'],
    ['code' => 'rn', 'name' => 'Rundi'],
    ['code' => 'rn-BI', 'name' => 'Rundi (Burundi)'],
    ['code' => 'ru', 'name' => 'Russian'],
    ['code' => 'ru-BY', 'name' => 'Russian (Belarus)'],
    ['code' => 'ru-KZ', 'name' => 'Russian (Kazakhstan)'],
    ['code' => 'ru-KG', 'name' => 'Russian (Kyrgyzstan)'],
    ['code' => 'ru-MD', 'name' => 'Russian (Moldova)'],
    ['code' => 'ru-RU', 'name' => 'Russian (Russia)'],
    ['code' => 'ru-UA', 'name' => 'Russian (Ukraine)'],
    ['code' => 'sg', 'name' => 'Sango'],
    ['code' => 'sg-CF', 'name' => 'Sango (Central African Republic)'],
    ['code' => 'gd', 'name' => 'Scottish Gaelic'],
    ['code' => 'gd-GB', 'name' => 'Scottish Gaelic (United Kingdom)'],
    ['code' => 'sr', 'name' => 'Serbian'],
    ['code' => 'sr-BA', 'name' => 'Serbian (Bosnia & Herzegovina)'],
    ['code' => 'sr-Cyrl-BA', 'name' => 'Serbian (Cyrillic, Bosnia & Herzegovina)'],
    ['code' => 'sr-Cyrl-XK', 'name' => 'Serbian (Cyrillic, Kosovo)'],
    ['code' => 'sr-Cyrl-ME', 'name' => 'Serbian (Cyrillic, Montenegro)'],
    ['code' => 'sr-Cyrl-RS', 'name' => 'Serbian (Cyrillic, Serbia)'],
    ['code' => 'sr-Cyrl', 'name' => 'Serbian (Cyrillic)'],
    ['code' => 'sr-XK', 'name' => 'Serbian (Kosovo)'],
    ['code' => 'sr-Latn-BA', 'name' => 'Serbian (Latin, Bosnia & Herzegovina)'],
    ['code' => 'sr-Latn-XK', 'name' => 'Serbian (Latin, Kosovo)'],
    ['code' => 'sr-Latn-ME', 'name' => 'Serbian (Latin, Montenegro)'],
    ['code' => 'sr-Latn-RS', 'name' => 'Serbian (Latin, Serbia)'],
    ['code' => 'sr-Latn', 'name' => 'Serbian (Latin)'],
    ['code' => 'sr-ME', 'name' => 'Serbian (Montenegro)'],
    ['code' => 'sr-RS', 'name' => 'Serbian (Serbia)'],
    ['code' => 'sh', 'name' => 'Serbo-Croatian'],
    ['code' => 'sh-BA', 'name' => 'Serbo-Croatian (Bosnia & Herzegovina)'],
    ['code' => 'sn', 'name' => 'Shona'],
    ['code' => 'sn-ZW', 'name' => 'Shona (Zimbabwe)'],
    ['code' => 'ii', 'name' => 'Sichuan Yi'],
    ['code' => 'ii-CN', 'name' => 'Sichuan Yi (China)'],
    ['code' => 'si', 'name' => 'Sinhala'],
    ['code' => 'si-LK', 'name' => 'Sinhala (Sri Lanka)'],
    ['code' => 'sk', 'name' => 'Slovak'],
    ['code' => 'sk-SK', 'name' => 'Slovak (Slovakia)'],
    ['code' => 'sl', 'name' => 'Slovenian'],
    ['code' => 'sl-SI', 'name' => 'Slovenian (Slovenia)'],
    ['code' => 'so', 'name' => 'Somali'],
    ['code' => 'so-DJ', 'name' => 'Somali (Djibouti)'],
    ['code' => 'so-ET', 'name' => 'Somali (Ethiopia)'],
    ['code' => 'so-KE', 'name' => 'Somali (Kenya)'],
    ['code' => 'so-SO', 'name' => 'Somali (Somalia)'],
    ['code' => 'es', 'name' => 'Spanish'],
    ['code' => 'es-AR', 'name' => 'Spanish (Argentina)'],
    ['code' => 'es-BO', 'name' => 'Spanish (Bolivia)'],
    ['code' => 'es-IC', 'name' => 'Spanish (Canary Islands)'],
    ['code' => 'es-EA', 'name' => 'Spanish (Ceuta & Melilla)'],
    ['code' => 'es-CL', 'name' => 'Spanish (Chile)'],
    ['code' => 'es-CO', 'name' => 'Spanish (Colombia)'],
    ['code' => 'es-CR', 'name' => 'Spanish (Costa Rica)'],
    ['code' => 'es-CU', 'name' => 'Spanish (Cuba)'],
    ['code' => 'es-DO', 'name' => 'Spanish (Dominican Republic)'],
    ['code' => 'es-EC', 'name' => 'Spanish (Ecuador)'],
    ['code' => 'es-SV', 'name' => 'Spanish (El Salvador)'],
    ['code' => 'es-GQ', 'name' => 'Spanish (Equatorial Guinea)'],
    ['code' => 'es-GT', 'name' => 'Spanish (Guatemala)'],
    ['code' => 'es-HN', 'name' => 'Spanish (Honduras)'],
    ['code' => 'es-MX', 'name' => 'Spanish (Mexico)'],
    ['code' => 'es-NI', 'name' => 'Spanish (Nicaragua)'],
    ['code' => 'es-PA', 'name' => 'Spanish (Panama)'],
    ['code' => 'es-PY', 'name' => 'Spanish (Paraguay)'],
    ['code' => 'es-PE', 'name' => 'Spanish (Peru)'],
    ['code' => 'es-PH', 'name' => 'Spanish (Philippines)'],
    ['code' => 'es-PR', 'name' => 'Spanish (Puerto Rico)'],
    ['code' => 'es-ES', 'name' => 'Spanish (Spain)'],
    ['code' => 'es-US', 'name' => 'Spanish (United States)'],
    ['code' => 'es-UY', 'name' => 'Spanish (Uruguay)'],
    ['code' => 'es-VE', 'name' => 'Spanish (Venezuela)'],
    ['code' => 'sw', 'name' => 'Swahili'],
    ['code' => 'sw-KE', 'name' => 'Swahili (Kenya)'],
    ['code' => 'sw-TZ', 'name' => 'Swahili (Tanzania)'],
    ['code' => 'sw-UG', 'name' => 'Swahili (Uganda)'],
    ['code' => 'sv', 'name' => 'Swedish'],
    ['code' => 'sv-AX', 'name' => 'Swedish (Åland Islands)'],
    ['code' => 'sv-FI', 'name' => 'Swedish (Finland)'],
    ['code' => 'sv-SE', 'name' => 'Swedish (Sweden)'],
    ['code' => 'tl', 'name' => 'Tagalog'],
    ['code' => 'tl-PH', 'name' => 'Tagalog (Philippines)'],
    ['code' => 'ta', 'name' => 'Tamil'],
    ['code' => 'ta-IN', 'name' => 'Tamil (India)'],
    ['code' => 'ta-MY', 'name' => 'Tamil (Malaysia)'],
    ['code' => 'ta-SG', 'name' => 'Tamil (Singapore)'],
    ['code' => 'ta-LK', 'name' => 'Tamil (Sri Lanka)'],
    ['code' => 'te', 'name' => 'Telugu'],
    ['code' => 'te-IN', 'name' => 'Telugu (India)'],
    ['code' => 'th', 'name' => 'Thai'],
    ['code' => 'th-TH', 'name' => 'Thai (Thailand)'],
    ['code' => 'bo', 'name' => 'Tibetan'],
    ['code' => 'bo-CN', 'name' => 'Tibetan (China)'],
    ['code' => 'bo-IN', 'name' => 'Tibetan (India)'],
    ['code' => 'ti', 'name' => 'Tigrinya'],
    ['code' => 'ti-ER', 'name' => 'Tigrinya (Eritrea)'],
    ['code' => 'ti-ET', 'name' => 'Tigrinya (Ethiopia)'],
    ['code' => 'to', 'name' => 'Tongan'],
    ['code' => 'to-TO', 'name' => 'Tongan (Tonga)'],
    ['code' => 'tr', 'name' => 'Turkish'],
    ['code' => 'tr-CY', 'name' => 'Turkish (Cyprus)'],
    ['code' => 'tr-TR', 'name' => 'Turkish (Turkey)'],
    ['code' => 'uk', 'name' => 'Ukrainian'],
    ['code' => 'uk-UA', 'name' => 'Ukrainian (Ukraine)'],
    ['code' => 'ur', 'name' => 'Urdu'],
    ['code' => 'ur-IN', 'name' => 'Urdu (India)'],
    ['code' => 'ur-PK', 'name' => 'Urdu (Pakistan)'],
    ['code' => 'ug', 'name' => 'Uyghur'],
    ['code' => 'ug-Arab-CN', 'name' => 'Uyghur (Arabic, China)'],
    ['code' => 'ug-Arab', 'name' => 'Uyghur (Arabic)'],
    ['code' => 'ug-CN', 'name' => 'Uyghur (China)'],
    ['code' => 'uz', 'name' => 'Uzbek'],
    ['code' => 'uz-AF', 'name' => 'Uzbek (Afghanistan)'],
    ['code' => 'uz-Arab-AF', 'name' => 'Uzbek (Arabic, Afghanistan)'],
    ['code' => 'uz-Arab', 'name' => 'Uzbek (Arabic)'],
    ['code' => 'uz-Cyrl-UZ', 'name' => 'Uzbek (Cyrillic, Uzbekistan)'],
    ['code' => 'uz-Cyrl', 'name' => 'Uzbek (Cyrillic)'],
    ['code' => 'uz-Latn-UZ', 'name' => 'Uzbek (Latin, Uzbekistan)'],
    ['code' => 'uz-Latn', 'name' => 'Uzbek (Latin)'],
    ['code' => 'uz-UZ', 'name' => 'Uzbek (Uzbekistan)'],
    ['code' => 'vi', 'name' => 'Vietnamese'],
    ['code' => 'vi-VN', 'name' => 'Vietnamese (Vietnam)'],
    ['code' => 'cy', 'name' => 'Welsh'],
    ['code' => 'cy-GB', 'name' => 'Welsh (United Kingdom)'],
    ['code' => 'fy', 'name' => 'Western Frisian'],
    ['code' => 'fy-NL', 'name' => 'Western Frisian (Netherlands)'],
    ['code' => 'yi', 'name' => 'Yiddish'],
    ['code' => 'yo', 'name' => 'Yoruba'],
    ['code' => 'yo-BJ', 'name' => 'Yoruba (Benin)'],
    ['code' => 'yo-NG', 'name' => 'Yoruba (Nigeria)'],
    ['code' => 'zu', 'name' => 'Zulu'],
    ['code' => 'zu-ZA', 'name' => 'Zulu (South Africa)']
];
